### PR TITLE
Add MoveEmbedding class

### PR DESCRIPTION
**Pull request by AdavyaB7**
Basic class setup to embed move information of Pokemon. 

Looking through [moves.ts](https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts), I use the following attributes which seem present in every move: 

- Categorical
  - type - 18 options (I did not include null type)
  - category - 3 options
  - target - 15 options
- Numerical
  - accuracy - this one is interesting: some values are true which I guess means move never misses. For now, I just reset it to 100 because I am not sure how they are different. 
  - basePower - should we just use the raw value or normalize this if we know a range like 0-255?
  - pp - same as above

I believe to start we should aim to include fewest number of most important attributes in our move embedding layer and only add complexity later. For example - not sure if we need to tackle priority (except maybe assign a fixed order like P1 always first followed by P2?), flags, contestType etc.

### CODE REVIEW

**Comment by aquapurity** [comment]
I think your approach for encoding the type / category / target / numerical data makes sense, but it is also not quite sufficient.

A lot of the power for many moves, and in particular almost all of the power for some extremely relevant moves, comes from a wide variety of status effects that must be encoded but aren't.

These are handled by the flags parameter for each move, but as I stated, these are highly varied. 

My initial plan was to simply make embeddings for each different move, and let the model handle figuring out all of the other move data. I thought this was potentially worth a try for an early model. However, combining what you have with my original intent of simply embedding each move might also be effective.

**Comment by AdavyaB7** [comment]
@PieBob851 Could you share an example of what you mean by "make embeddings for each different move"? 

If we were to use the MoveEmbedding class, how do you suggest encoding secondary or flags info since they are highly varied? 

`flags: {protect: 1, mirror: 1, metronome: 1, bullet: 1}`
`secondary: {
	chance: 100,
	boosts: {
		spd: -2,
	},}`

**Comment by aquapurity** [comment]
I think embedding secondary info / flags could work, I'm just not sure if that covers all the information.

By "make embeddings for each different move", I meant simply taking the move name, getting an id for it from a dictionary, and then embedding that - for a dictionary of all ~1000 or so moves which exist (basically, similar to work token embeddings which have fairly large dictionaries) - so the move Tackle would be embedded completely (e.g. "tackle" has id 1 perhaps, and then 1 is embedded, "hyperbeam" has id 800 and is embedded, etc)

**Comment by AdavyaB7** [comment]
Ah I see, that simplifies things a lot. I think we can then just use num which identifies each move as the move ID and then embed it. Okay let me work on that. I was originally trying to embed each detail of the move separately to embed the overall move.

**Comment by AdavyaB7** [comment]
@PieBob851 simplified things -- is this more like what you had imagined? Also there's two moves from the .ts file that I did not include (paleowave and shadowstrike) both CAP moves. I tried parsing the file but I couldn't get a clean dictionary output that way so I decided to look online for a moves spreadsheet and found one that matches the .ts file from the simulator. 

Confirmed for a few moves that the identifiers `num` match although there's few that are randomly omitted like there exists no move with num as 623 for instance.

**Review by ljones315 — COMMENTED** [review]
nice! Just to make sure my understanding is right:
- the showdown server will give us a list of possible moves for our active pokemon (in the request object)
- we embed those and pass them to our model
- model selects the best move
- we decode it (maybe want a backward function in this class? just the reverse lookup) and send it to the server

and then we also consider whether or not to use an ability or to switch the active pokemon to the bench which will be embeddings of their own?

**Comment by AdavyaB7** [comment]
@ljones315 My understanding is as follows: 

- We provide the current state of the game and list of possible actions (hopefully the server gives us these) as inputs to our model. Current state is just HP, active pokemon etc. Possible actions include 4 valid moves for current pokemon + up to 5 valid switches for benched pokemons. 
- Embed everything and pass to the model. 
- The model outputs a probability distribution over all possible actions. We choose best one which could be a move or switch and return that to the server and repeat the process. 

Now, the details of actual model architecture are up for discussion. Somewhere along the way, we also need to incorporate PPO and calculate expected value / loss / reward to see if the model is actually training well.

**Pull request merged**
